name: pull request comment
on:
  # Trigger the workflow on pull request comment
  pull_request:
    branches:
      - main
      - branch-1

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.event.comment.body,build now
              body: 'comment on pr'
            })
