name: pull request comment
on:
  issue_comment:                                     
    types: [created, deleted]
jobs:
 job01:
   if: contains(github.event.issue.pull_request, '/build now')    # check if the comments come from pull request, exclude those from issue.
   runs-on: ubuntu-latest
   steps:
    - name: say hello
      if: contains(github.event.issue.pull_request, '/build now')   # check the comment if it contains the keywords
      run: |
       echo say hello
    - name: test
      if: contains(github.event.issue.pull_request, '/build now')  # check the comment if it contains the keywords
      run: |
       echo test
