name: pull request comment

on:
  issue_comment:
    types: [created, deleted]

jobs:
  comment:
    if: contains(github.event.comment.body, 'build now')

    runs-on: ubuntu-latest

    steps:
      - name: pr_comment
        env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}
