name: PR comments
on:
  pull_request:
    branches: [ "main" ]
  issue_comment:
    types: [created, deleted]
jobs:
  prcomment:
    name: Read PR Comments
    runs-on: ubuntu-latest
    steps:
    - run: gem install octokit -v 4.15.0 --user-install
    - uses: actions/checkout@v3
    - run: ruby -r ./.github/workflows/octokit.rb
    - run: sh ./.github/workflows/datetime.sh
  pr_commented:
  # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ManiSakhi/PR-comment/comment-on-pr@branch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
